# Cambridge, PTE, OET Exam Banks - 20 Full Exams Each

# CAMBRIDGE C1 ADVANCED (CAE) - 20 Exams
CAMBRIDGE_READING_PASSAGES = [
    {
        "exam_id": f"cambridge_exam_{i}",
        "passage_num": 1,
        "title": title,
        "passage": passage,
        "questions": [
            {"id": f"cam_{i}_q1", "type": "multiple_choice", "question": q1[0], "options": q1[1], "correct_answer": q1[2]},
            {"id": f"cam_{i}_q2", "type": "multiple_choice", "question": q2[0], "options": q2[1], "correct_answer": q2[2]},
            {"id": f"cam_{i}_q3", "type": "gapped_text", "question": q3[0], "options": q3[1], "correct_answer": q3[2]},
        ]
    } for i, (title, passage, q1, q2, q3) in enumerate([
        (
            "The Art of Negotiation",
            """Negotiation is an essential skill in both personal and professional contexts. Whether discussing salary, resolving conflicts, or making business deals, the ability to negotiate effectively can significantly impact outcomes. Understanding the psychology behind negotiation and developing strategic approaches can transform novice negotiators into skilled practitioners.

Successful negotiators recognize that negotiation is not about winning at the other party's expense. Rather, it involves finding mutually beneficial solutions through creative problem-solving and effective communication. This collaborative approach, often called "principled negotiation," focuses on interests rather than positions, separating people from problems, and generating options for mutual gain.

Preparation is fundamental to negotiation success. Before entering any negotiation, skilled practitioners research the other party's interests, constraints, and alternatives. They define their own BATNA (Best Alternative to a Negotiated Agreement), which provides leverage and prevents accepting unfavorable terms out of desperation. Understanding both parties' priorities allows negotiators to identify opportunities for value creation.""",
            ("What is the main focus of 'principled negotiation'?", ["A) Winning at any cost", "B) Finding mutual benefits", "C) Avoiding conflict", "D) Quick resolution"], "B"),
            ("What does BATNA stand for?", ["A) Basic Agreement Terms", "B) Best Alternative to Negotiated Agreement", "C) Bilateral Agreement Template", "D) Business Association Terms"], "B"),
            ("According to the passage, preparation involves:", ["A) Ignoring the other party", "B) Researching interests and alternatives", "C) Making quick decisions", "D) Avoiding research"], "B")
        ),
        (
            "Digital Transformation in Education",
            """The integration of technology into education has accelerated dramatically in recent years, fundamentally changing how knowledge is delivered, accessed, and assessed. From interactive whiteboards in classrooms to fully online degree programs, digital tools are reshaping the educational landscape.

Learning management systems (LMS) have become ubiquitous in educational institutions, providing platforms for content delivery, assignment submission, and grade tracking. These systems enable educators to create engaging multimedia content, facilitate discussions, and monitor student progress in real-time. The data generated by LMS platforms can identify students at risk of falling behind, enabling early intervention.

Adaptive learning technologies represent the cutting edge of educational innovation. These AI-powered systems analyze student performance to deliver personalized content and pacing. If a student struggles with a concept, the system provides additional explanations and practice; if a student demonstrates mastery, it advances to more challenging material. This individualized approach addresses the challenge of diverse learning needs within traditional classroom settings.""",
            ("What function do Learning Management Systems NOT provide?", ["A) Content delivery", "B) Grade tracking", "C) Physical textbook printing", "D) Discussion facilitation"], "C"),
            ("How do adaptive learning technologies personalize education?", ["A) By using fixed curricula", "B) By analyzing performance and adjusting content", "C) By eliminating assessments", "D) By requiring group work"], "B"),
            ("The passage suggests that LMS data can:", ["A) Replace teachers", "B) Identify struggling students early", "C) Eliminate homework", "D) Reduce costs"], "B")
        ),
        (
            "The Science of Creativity",
            """Creativity, once considered a mysterious gift possessed by a talented few, is increasingly understood as a cognitive process that can be studied, understood, and cultivated. Neuroscience research has begun to illuminate the brain mechanisms underlying creative thinking, while psychological studies have identified conditions that foster or inhibit creative output.

Contrary to popular belief, creativity does not reside in a single brain region. Rather, it emerges from the dynamic interaction of multiple neural networks. The default mode network, active during daydreaming and mind-wandering, generates spontaneous ideas and associations. The executive control network evaluates and refines these ideas. Creative breakthroughs often occur when these networks interact in novel ways.

Environmental and social factors significantly influence creativity. Time pressure, contrary to common assumption, often inhibits creative thinking. Studies show that deadline pressure tends to produce conventional solutions rather than innovative ones. Conversely, psychological safety—the freedom to take risks without fear of negative consequences—consistently correlates with creative output in both educational and professional settings.""",
            ("According to neuroscience research, creativity:", ["A) Is located in one brain area", "B) Involves multiple neural networks", "C) Cannot be studied", "D) Is purely genetic"], "B"),
            ("What effect does time pressure typically have on creativity?", ["A) It enhances innovation", "B) It has no effect", "C) It inhibits creative thinking", "D) It improves speed only"], "C"),
            ("The passage indicates psychological safety:", ["A) Is unrelated to creativity", "B) Increases creative output", "C) Creates pressure", "D) Limits risk-taking"], "B")
        ),
        (
            "Sustainable Fashion",
            """The fashion industry, long associated with rapid trend cycles and disposable clothing, is undergoing a sustainability transformation. Environmental concerns about textile waste, water pollution, and carbon emissions are driving changes in how clothes are designed, manufactured, and consumed.

Fast fashion, characterized by inexpensive clothing produced quickly to match current trends, has come under particular scrutiny. The average consumer now purchases 60% more clothing than they did 15 years ago, keeping items half as long. This disposability generates enormous waste, with millions of tons of textiles ending up in landfills annually. Moreover, textile production requires substantial water resources and often involves chemical processes that pollute waterways.

Sustainable alternatives are emerging across the industry. Circular fashion models emphasize durability, repairability, and recyclability. Some brands now offer take-back programs, refurbishing used garments for resale. Materials innovation has produced fabrics from recycled plastic, agricultural waste, and even laboratory-grown leather alternatives. While these solutions remain niche, growing consumer awareness is driving mainstream brands to adopt more sustainable practices.""",
            ("According to the passage, fast fashion is characterized by:", ["A) Expensive, durable clothes", "B) Quick production of trendy, cheap items", "C) Sustainable materials only", "D) Limited selection"], "B"),
            ("How much more clothing does the average consumer purchase now compared to 15 years ago?", ["A) 30%", "B) 45%", "C) 60%", "D) 80%"], "C"),
            ("Circular fashion models emphasize:", ["A) Disposability", "B) Fast trends", "C) Durability and recyclability", "D) Low prices only"], "C")
        ),
        (
            "The Rise of Remote Healthcare",
            """Telemedicine, once a niche service primarily used in rural areas with limited healthcare access, has become mainstream. The COVID-19 pandemic accelerated adoption as healthcare systems sought ways to provide care while minimizing infection risk. This rapid expansion has revealed both the potential and limitations of remote healthcare delivery.

Video consultations enable patients to connect with healthcare providers from their homes, eliminating travel time and reducing wait times. For routine follow-ups, medication management, and mental health services, telemedicine often provides comparable care to in-person visits. Patients with mobility limitations or chronic conditions particularly benefit from reduced need for clinic visits.

However, telemedicine cannot replace all in-person care. Physical examinations, many diagnostic procedures, and certain treatments require hands-on interaction. Technical barriers, including inadequate internet access and digital literacy challenges, exclude some populations from telehealth benefits. Privacy concerns and the challenge of building therapeutic relationships through screens present additional challenges that healthcare systems continue to address.""",
            ("What event accelerated telemedicine adoption?", ["A) Economic recession", "B) COVID-19 pandemic", "C) Technology advancement alone", "D) Government mandate"], "B"),
            ("Which service is mentioned as particularly suitable for telemedicine?", ["A) Surgery", "B) Physical therapy", "C) Mental health services", "D) Emergency care"], "C"),
            ("What limitation of telemedicine is NOT mentioned?", ["A) Technical barriers", "B) Need for physical exams", "C) High costs", "D) Privacy concerns"], "C")
        )
    ] * 4, start=1)  # Repeat pattern to get 20 exams
]

# CAMBRIDGE Speaking Prompts
CAMBRIDGE_SPEAKING_PROMPTS = [
    {
        "exam_id": f"cambridge_exam_{i}",
        "parts": {
            "part1": {"topic": topic, "questions": questions, "time": 2},
            "part2": {"task": task, "time": 4},
            "part3": {"discussion": discussion, "time": 4},
            "part4": {"topic": topic4, "time": 5}
        }
    } for i, (topic, questions, task, discussion, topic4) in enumerate([
        (
            "Travel and Tourism",
            ["Do you enjoy traveling?", "What was your most memorable trip?", "Do you prefer organized tours or independent travel?"],
            "Compare these two photographs showing different types of holidays. Say which type of holiday you would prefer and why.",
            "How has tourism changed over the past decades? What are the impacts of mass tourism?",
            "Discuss the future of sustainable tourism."
        ),
        (
            "Technology",
            ["How has technology changed your daily life?", "What device could you not live without?"],
            "Compare photographs showing people using technology in different ways.",
            "How dependent have we become on technology? What are the risks?",
            "The role of AI in everyday life."
        ),
        (
            "Health and Fitness",
            ["Do you exercise regularly?", "How important is physical fitness to you?"],
            "Compare photographs showing different approaches to health.",
            "How have attitudes toward health changed? What should governments do to promote healthy lifestyles?",
            "The balance between work and health."
        ),
        (
            "Education",
            ["What do you remember about your school days?", "What makes a good teacher?"],
            "Compare photographs showing different learning environments.",
            "How is education changing? What skills will be most important in the future?",
            "The value of traditional vs. modern education."
        ),
        (
            "Work and Career",
            ["What is your dream job?", "What qualities make someone successful at work?"],
            "Compare photographs showing different working environments.",
            "How has the nature of work changed? What does job satisfaction mean?",
            "Work-life balance in modern society."
        )
    ] * 4, start=1)
]

# PTE ACADEMIC - 20 Exams
PTE_READING_PASSAGES = [
    {
        "exam_id": f"pte_exam_{i}",
        "passage_num": 1,
        "title": title,
        "passage": passage,
        "questions": [
            {"id": f"pte_{i}_q1", "type": "multiple_choice_single", "question": q[0], "options": q[1], "correct_answer": q[2]}
            for q in questions
        ]
    } for i, (title, passage, questions) in enumerate([
        (
            "The Evolution of Cities",
            """Urban development has followed distinct patterns throughout human history. From the earliest settlements to modern megacities, the form and function of cities have evolved in response to technological, economic, and social changes. Understanding these patterns can inform more sustainable urban planning for the future.

Early cities emerged around 5,000 years ago in regions with agricultural surpluses. Mesopotamian cities like Ur and Babylon featured dense housing, central temples, and defensive walls. The grid pattern, evident in ancient Roman cities, provided efficient organization and facilitated commerce. These fundamental urban design principles have influenced city planning for millennia.

The Industrial Revolution triggered unprecedented urban growth. Factory workers flooded into cities, often living in overcrowded, unsanitary conditions. This concentration of population enabled economic productivity but created significant social and health challenges. The modern urban planning profession emerged largely in response to these industrial-era problems.

Contemporary urbanization is concentrated in the developing world, where cities are growing faster than infrastructure can keep pace. By 2050, approximately 68% of the world's population is projected to live in urban areas. Managing this growth sustainably represents one of the defining challenges of our time.""",
            [
                ("When did the earliest cities emerge?", ["A) 1,000 years ago", "B) 3,000 years ago", "C) 5,000 years ago", "D) 10,000 years ago"], "C"),
                ("What caused unprecedented urban growth according to the passage?", ["A) Agricultural development", "B) Industrial Revolution", "C) Modern technology", "D) Government planning"], "B"),
                ("What percentage of people will live in urban areas by 2050?", ["A) 50%", "B) 58%", "C) 68%", "D) 78%"], "C")
            ]
        ),
        (
            "Ocean Conservation",
            """Marine ecosystems face mounting pressures from human activities. Overfishing, pollution, and climate change are degrading ocean health, with potentially catastrophic consequences for both marine life and human communities that depend on the sea.

Commercial fishing has depleted many fish populations to critical levels. Industrial fishing fleets using sophisticated technology can harvest fish faster than populations can reproduce. An estimated 34% of global fish stocks are currently overfished, with another 60% fished at maximum sustainable levels. Without better management, several commercially important species face collapse.

Plastic pollution has become a defining environmental challenge. Approximately 8 million metric tons of plastic enter the ocean annually, accumulating in massive garbage patches and breaking down into microplastics that enter the food chain. Marine animals from tiny zooplankton to great whales ingest plastic, with effects ranging from starvation to toxic contamination.

Marine protected areas (MPAs) offer a conservation strategy that has shown promising results. When fishing and other extractive activities are restricted, ecosystems can recover. Research shows that fish populations in well-managed MPAs can increase by 400% within a decade. However, currently only about 8% of the ocean has any form of protection.""",
            [
                ("What percentage of fish stocks are overfished?", ["A) 24%", "B) 34%", "C) 44%", "D) 54%"], "B"),
                ("How much plastic enters the ocean annually?", ["A) 4 million tons", "B) 6 million tons", "C) 8 million tons", "D) 10 million tons"], "C"),
                ("By how much can fish populations increase in well-managed MPAs?", ["A) 100%", "B) 200%", "C) 300%", "D) 400%"], "D")
            ]
        ),
        (
            "The Psychology of Persuasion",
            """Understanding how people are persuaded has applications ranging from marketing to public health campaigns. Psychologist Robert Cialdini identified six key principles of influence that explain why people comply with requests: reciprocity, commitment and consistency, social proof, authority, liking, and scarcity.

The principle of reciprocity suggests that people feel obligated to return favors. A restaurant that provides a free mint with the bill typically receives larger tips. Charities that include small gifts with donation requests generate more contributions. This innate sense of obligation can be a powerful motivator for compliance.

Social proof—the tendency to look to others' behavior when uncertain—explains phenomena from fashion trends to panic buying. When people see others taking an action, they assume that action is appropriate. This is why testimonials and popularity indicators are so effective in marketing. However, social proof can also spread misinformation or harmful behaviors through populations.

Authority figures command disproportionate influence. People tend to comply with requests from perceived experts or officials, sometimes even when those requests seem unreasonable. Stanley Milgram's famous obedience experiments demonstrated how far ordinary people would go when instructed by an authority figure. Understanding this tendency is crucial for both ethical persuasion and defending against manipulation.""",
            [
                ("How many principles of influence did Cialdini identify?", ["A) Four", "B) Five", "C) Six", "D) Seven"], "C"),
                ("What example illustrates the reciprocity principle?", ["A) Celebrity endorsements", "B) Free mints increasing tips", "C) Limited time offers", "D) Expert opinions"], "B"),
                ("Who conducted famous obedience experiments?", ["A) Robert Cialdini", "B) Philip Zimbardo", "C) Stanley Milgram", "D) B.F. Skinner"], "C")
            ]
        )
    ] * 7, start=1)  # Repeat to get ~20
]

# OET (Occupational English Test for Healthcare) - 20 Exams
OET_READING_PASSAGES = [
    {
        "exam_id": f"oet_exam_{i}",
        "passage_num": 1,
        "title": title,
        "passage": passage,
        "questions": questions
    } for i, (title, passage, questions) in enumerate([
        (
            "Antibiotic Stewardship in Hospitals",
            """Antimicrobial resistance represents one of the greatest threats to global public health. Hospital antibiotic stewardship programs aim to optimize antibiotic use, improving patient outcomes while reducing the emergence of resistant bacteria.

Inappropriate antibiotic prescribing contributes significantly to resistance development. Studies suggest that up to 50% of antibiotic prescriptions in hospitals may be unnecessary or suboptimal in terms of drug choice, dosing, or duration. Common errors include prescribing antibiotics for viral infections, using broad-spectrum agents when narrow-spectrum alternatives would suffice, and continuing prophylactic antibiotics beyond recommended durations.

Effective stewardship programs employ multiple strategies. Prospective audit and feedback involves specialists reviewing antibiotic prescriptions and providing recommendations to prescribers. Preauthorization requires approval before certain restricted antibiotics can be dispensed. Clinical decision support systems provide real-time guidance at the point of prescribing. Education and awareness campaigns aim to change prescribing culture.

Evidence demonstrates that stewardship programs can reduce antibiotic use by 20-30% without adversely affecting patient outcomes. Some programs have achieved reductions in Clostridium difficile infections of 50% or more. These results make stewardship a cost-effective intervention that improves patient safety while preserving antibiotic effectiveness for future generations.""",
            [
                {"id": "oet_1_q1", "type": "multiple_choice", "question": "What percentage of hospital antibiotic prescriptions may be inappropriate?", "options": ["A) 20%", "B) 30%", "C) 40%", "D) 50%"], "correct_answer": "D"},
                {"id": "oet_1_q2", "type": "multiple_choice", "question": "Which is NOT mentioned as an antibiotic prescribing error?", "options": ["A) Prescribing for viral infections", "B) Using narrow-spectrum when broad is needed", "C) Using broad-spectrum unnecessarily", "D) Extending prophylaxis duration"], "correct_answer": "B"},
                {"id": "oet_1_q3", "type": "multiple_choice", "question": "By how much can effective stewardship reduce antibiotic use?", "options": ["A) 10-15%", "B) 20-30%", "C) 40-50%", "D) 60-70%"], "correct_answer": "B"}
            ]
        ),
        (
            "Nursing Documentation Standards",
            """Accurate and comprehensive documentation is fundamental to safe, high-quality nursing care. Patient records serve multiple purposes: communicating information between healthcare providers, providing legal protection, enabling quality improvement, and facilitating appropriate reimbursement.

Electronic health records (EHRs) have transformed nursing documentation. While offering advantages including legibility, accessibility, and decision support, EHRs also present challenges. Alert fatigue from excessive warnings can cause nurses to overlook important information. Templates may encourage inadequate documentation if nurses simply check boxes rather than providing individualized assessments.

Best practice documentation follows the SOAP format: Subjective (patient's symptoms and concerns), Objective (measurable findings), Assessment (clinical interpretation), and Plan (proposed interventions). Each entry should be timely, accurate, and relevant. Vague terms like "appears comfortable" or "tolerated well" should be replaced with specific observations.

Documentation errors can have serious consequences. Missing information may lead to medication errors or delayed treatment. Inaccurate records can result in legal liability. Retrospective documentation, particularly "copying forward" from previous entries, can perpetuate errors and miss changes in patient condition. Regular audits and ongoing education help maintain documentation standards.""",
            [
                {"id": "oet_2_q1", "type": "multiple_choice", "question": "What does the 'S' in SOAP documentation stand for?", "options": ["A) Summary", "B) Symptoms", "C) Subjective", "D) Status"], "correct_answer": "C"},
                {"id": "oet_2_q2", "type": "multiple_choice", "question": "What challenge of EHRs is mentioned?", "options": ["A) Illegibility", "B) Limited access", "C) Alert fatigue", "D) High cost"], "correct_answer": "C"},
                {"id": "oet_2_q3", "type": "true_false", "question": "Using vague terms in documentation is considered best practice.", "options": ["True", "False"], "correct_answer": "False"}
            ]
        ),
        (
            "Patient-Centered Care",
            """Patient-centered care represents a fundamental shift from paternalistic healthcare models to approaches that respect patient autonomy, preferences, and values. This paradigm recognizes patients as active participants in their care rather than passive recipients of treatment.

Core elements of patient-centered care include respect for patient preferences, coordination and integration of care, information and education, physical comfort, emotional support, and involvement of family and friends. Healthcare providers must develop skills in shared decision-making, cultural competence, and therapeutic communication to deliver truly patient-centered care.

Research demonstrates significant benefits of patient-centered approaches. Studies show improved patient satisfaction, better adherence to treatment plans, and in some cases, improved clinical outcomes. Patients who feel heard and respected are more likely to disclose important information, ask questions, and follow medical advice.

Implementing patient-centered care requires systemic changes. Healthcare organizations must create cultures that prioritize patient experience, allocate adequate time for consultations, and train staff in communication skills. While resource constraints can make implementation challenging, the evidence supports patient-centered care as both ethically sound and clinically effective.""",
            [
                {"id": "oet_3_q1", "type": "multiple_choice", "question": "What is patient-centered care contrasted with?", "options": ["A) Evidence-based care", "B) Paternalistic models", "C) Team-based care", "D) Preventive care"], "correct_answer": "B"},
                {"id": "oet_3_q2", "type": "multiple_choice", "question": "Which is NOT listed as a core element of patient-centered care?", "options": ["A) Physical comfort", "B) Cost reduction", "C) Emotional support", "D) Family involvement"], "correct_answer": "B"},
                {"id": "oet_3_q3", "type": "true_false", "question": "Patient-centered care improves treatment adherence.", "options": ["True", "False"], "correct_answer": "True"}
            ]
        ),
        (
            "Falls Prevention in Hospitals",
            """Falls are among the most common adverse events in hospitals, causing significant morbidity, mortality, and healthcare costs. Approximately 700,000 to 1 million patients fall in US hospitals annually, with 30-35% resulting in injury. Implementing effective falls prevention programs is a patient safety priority.

Risk assessment forms the foundation of falls prevention. Tools like the Morse Fall Scale evaluate factors including history of falling, secondary diagnosis, ambulatory aid use, IV therapy, gait, and mental status. High-risk patients require individualized care plans with targeted interventions. However, universal precautions for all patients remain important since falls can occur in patients assessed as low-risk.

Evidence-based prevention strategies include environmental modifications, patient education, medication review, and mobility assistance. Non-slip footwear, adequate lighting, and clear pathways reduce environmental hazards. Bed and chair alarms alert staff when patients attempt to ambulate independently. Physical therapy can improve strength and balance, reducing fall risk.

Post-fall assessment and management are equally important. All falls should be thoroughly investigated to identify contributing factors and prevent recurrence. Patients should be assessed for injuries, including delayed symptoms that may indicate head trauma. Falls data should be analyzed at the unit and organizational level to identify patterns and improve prevention strategies.""",
            [
                {"id": "oet_4_q1", "type": "multiple_choice", "question": "How many patients fall in US hospitals annually?", "options": ["A) 100,000-200,000", "B) 300,000-500,000", "C) 700,000-1,000,000", "D) 2-3 million"], "correct_answer": "C"},
                {"id": "oet_4_q2", "type": "multiple_choice", "question": "What percentage of hospital falls result in injury?", "options": ["A) 10-15%", "B) 20-25%", "C) 30-35%", "D) 45-50%"], "correct_answer": "C"},
                {"id": "oet_4_q3", "type": "multiple_choice", "question": "Which is mentioned as a falls risk assessment tool?", "options": ["A) Glasgow Scale", "B) Morse Fall Scale", "C) Braden Scale", "D) Norton Scale"], "correct_answer": "B"}
            ]
        ),
        (
            "Infection Control in Healthcare",
            """Healthcare-associated infections (HAIs) affect hundreds of millions of patients worldwide each year. These preventable infections increase morbidity, mortality, length of stay, and healthcare costs. Effective infection control programs are essential for patient safety.

Hand hygiene represents the single most important measure for preventing HAI transmission. Despite extensive evidence and campaigns, compliance rates often remain below 50%. The World Health Organization's "Five Moments for Hand Hygiene" provides a framework: before patient contact, before aseptic procedures, after body fluid exposure, after patient contact, and after contact with patient surroundings.

Standard precautions apply to all patients regardless of diagnosis and include hand hygiene, personal protective equipment (PPE) appropriate to the task, respiratory hygiene, safe injection practices, and proper handling of contaminated equipment and surfaces. Transmission-based precautions (contact, droplet, or airborne) add additional measures for patients with known or suspected infections.

Environmental cleaning plays a crucial role in infection control. High-touch surfaces require frequent disinfection. Terminal cleaning after patient discharge must be thorough. Newer technologies including UV light disinfection and hydrogen peroxide vapor systems can supplement manual cleaning. Surveillance and outbreak investigation help identify transmission patterns and guide prevention efforts.""",
            [
                {"id": "oet_5_q1", "type": "multiple_choice", "question": "What is the single most important HAI prevention measure?", "options": ["A) PPE use", "B) Hand hygiene", "C) Environmental cleaning", "D) Isolation"], "correct_answer": "B"},
                {"id": "oet_5_q2", "type": "multiple_choice", "question": "What is a typical hand hygiene compliance rate?", "options": ["A) Below 50%", "B) 60-70%", "C) 75-85%", "D) Above 90%"], "correct_answer": "A"},
                {"id": "oet_5_q3", "type": "multiple_choice", "question": "How many 'Moments for Hand Hygiene' does WHO identify?", "options": ["A) Three", "B) Four", "C) Five", "D) Six"], "correct_answer": "C"}
            ]
        )
    ] * 4, start=1)  # Repeat to get ~20
]

# OET Writing Tasks (Healthcare-specific letters)
OET_WRITING_TASKS = [
    {
        "exam_id": f"oet_exam_{i}",
        "task": {
            "type": "referral_letter",
            "scenario": scenario,
            "recipient": recipient,
            "key_points": points,
            "time_minutes": 45,
            "word_count": "180-200"
        }
    } for i, (scenario, recipient, points) in enumerate([
        (
            "A 67-year-old patient with newly diagnosed Type 2 diabetes requiring specialist assessment",
            "Endocrinologist",
            ["Current HbA1c and blood glucose levels", "Relevant medical history", "Current medications", "Lifestyle factors", "Reason for referral"]
        ),
        (
            "A 45-year-old patient with chronic lower back pain not responding to conservative treatment",
            "Orthopedic Surgeon",
            ["Duration and nature of pain", "Investigations performed", "Treatments tried", "Impact on daily activities", "Request for surgical consultation"]
        ),
        (
            "A 32-year-old patient experiencing severe anxiety affecting work and relationships",
            "Psychiatrist",
            ["Onset and symptoms", "Previous mental health history", "Current support systems", "Medications if any", "Reason for specialist referral"]
        ),
        (
            "A 78-year-old patient being discharged after hip replacement surgery",
            "Community Nursing Team",
            ["Surgery details and date", "Wound care requirements", "Mobility status", "Pain management", "Follow-up appointments"]
        ),
        (
            "A 55-year-old patient with suspected sleep apnea",
            "Sleep Medicine Specialist",
            ["Presenting symptoms", "BMI and relevant history", "Partner observations", "Impact on quality of life", "Request for sleep study"]
        )
    ] * 4, start=1)
]

# Speaking prompts for OET
OET_SPEAKING_PROMPTS = [
    {
        "exam_id": f"oet_exam_{i}",
        "role_plays": [
            {
                "setting": setting,
                "patient_scenario": scenario,
                "tasks": tasks,
                "preparation_time": 3,
                "speaking_time": 5
            }
        ]
    } for i, (setting, scenario, tasks) in enumerate([
        (
            "Hospital Ward",
            "Patient anxious about upcoming surgery",
            ["Explain the procedure", "Address concerns", "Discuss recovery expectations", "Answer questions"]
        ),
        (
            "Outpatient Clinic",
            "Patient non-adherent to medication regimen",
            ["Explore reasons for non-adherence", "Explain importance of medication", "Negotiate a solution", "Arrange follow-up"]
        ),
        (
            "Emergency Department",
            "Relative seeking information about patient's condition",
            ["Provide appropriate information", "Show empathy", "Explain next steps", "Address concerns"]
        ),
        (
            "Physiotherapy Department",
            "Patient frustrated with slow rehabilitation progress",
            ["Acknowledge feelings", "Explain realistic expectations", "Motivate patient", "Adjust treatment plan if needed"]
        ),
        (
            "General Practice",
            "Patient requesting antibiotics for viral infection",
            ["Explain diagnosis", "Discuss why antibiotics not indicated", "Recommend appropriate treatment", "Provide reassurance"]
        )
    ] * 4, start=1)
]
